# === HOÀN THIỆN TOÀN BỘ: CHỐNG CHẶN TỐI ƯU + TỰ LẤY/NHẬN BỔ SUNG + PHÂN TÍCH XỔ SỐ + ĐÁNH GIÁ UPCOM ===
import os, random
from flask import Flask
from threading import Thread
import time, telebot, requests
from bs4 import BeautifulSoup
from collections import Counter
from datetime import datetime, timedelta
app = Flask(__name__)
@app.route('/')
def giu_song(): return "✅ Hoàn chỉnh: Truy cập giống người dùng thật, luân phiên nguồn, nhận dữ liệu bạn gửi, phân tích đủ chức năng!"
def chay_server(): app.run(host="0.0.0.0", port=int(os.environ.get("PORT",8080)))
Thread(target=chay_server).start()
BOT_TOKEN = "8520938638:AAEHwQp89_P2slG7YTkod4z6_XvYbgBD7ns"; CHAT_ID = 7064473358; bot = telebot.TeleBot(BOT_TOKEN); DA_CO_DU_LIEU = {}; DS_LINK_NGUON = ["https://ketqua.vn/xo-so-mien-bac/ngay-{d}-{m}-{y}","https://xoso.me/xsmb-{d}-{m}-{y}","https://xoso.com.vn/kqxs-mien-bac-ngay-{d}-{m}-{y}.html"]
def tinh_diem_chuan(danh_sach_duoi): dem_so_lan=Counter(danh_sach_duoi); vi_tri_tung_lan={}; [vi_tri_tung_lan.setdefault(m,[]).append(vt) for vt,m in enumerate(danh_sach_duoi)]; ds_diem=[]; [ds_diem.append((-round(so_lan*4.0+(round(10/(1+(max(khoang_cach)-min(khoang_cach) if khoang_cach else 1)),2))*10,2),m,so_lan)) if (khoang_cach:=[vi_tri[i]-vi_tri[i-1] for i in range(1,len(vi_tri))]) else ds_diem.append((-so_lan*2.5,m,so_lan))) for m,so_lan,vi_tri in zip(dem_so_lan.keys(),dem_so_lan.values(),vi_tri_tung_lan.values())]; ds_diem.sort(); top3=[(m,sl) for _,m,sl in ds_diem[:3]]; top20=[m for _,m,_ in ds_diem[:20]]; return top3,top20
def lay_an_toan(ngay_obj): khoa_ngay=ngay_obj.strftime("%d/%m/%Y"); if khoa_ngay in DA_CO_DU_LIEU: return DA_CO_DU_LIEU[khoa_ngay]; DS_HEADER=[{"User-Agent":"Mozilla/5.0 (Linux; Android 14; SM-G998B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Mobile Safari/537.36","Accept-Language":"vi-VN,vi;q=0.9,en-US;q=0.8,en;q=0.7","Referer":"https://www.google.com/"},{"User-Agent":"Mozilla/5.0 (Linux; Android 13; Redmi Note12) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Mobile Safari/537.36","Accept-Language":"vi-VN,vi;q=0.9","Referer":"https://ketqua.vn/"}]; [ ( (res:=requests.get(link_mau.format(d=ngay_obj.day,m=ngay_obj.month,y=ngay_obj.year),headers=random.choice(DS_HEADER),timeout=9)), (soup:=BeautifulSoup(res.text,"html.parser")), (ds_so:=[chuoi[-2:] for chuoi in [the.get_text(strip=True) for the in soup.select("span.prize-number, span.number, div.prize span")] if chuoi.isdigit() and len(chuoi)>=2]), len(ds_so)>=25 and (DA_CO_DU_LIEU.update({khoa_ngay:ds_so}), return ds_so)) or time.sleep(random.uniform(0.6,1.1)) for link_mau in DS_LINK_NGUON for _ in range(2) ]; return None
@bot.message_handler(func=lambda msg: msg.text.strip().startswith("Luu du lieu:"))
def xu_ly_luu_ban_gui(msg): try: noi_dung=msg.text.strip().replace("Luu du lieu:","").strip(); phan_ngay=noi_dung.split("|")[0].replace("Ngày","").strip(); danh_sach_duoi=[d.strip() for d in noi_dung.split("|")[1].replace("Đuôi:","").strip().split(",") if d.strip() and len(d.strip())==2]; ngay_chuan=datetime.strptime(phan_ngay,"%d/%m/%Y").strftime("%d/%m/%Y"); DA_CO_DU_LIEU[ngay_chuan]=danh_sach_duoi; bot.send_message(msg.chat.id,f"✅ ĐÃ LƯU THÀNH CÔNG NGÀY: {ngay_chuan}\nSố đuôi nhận được: {len(danh_sach_duoi)} số, sẵn sàng phân tích chung!") except: bot.send_message(msg.chat.id,"⚠️ Dùng mẫu: Luu du lieu: Ngày 22/08/2026 | Đuôi: 00,07,09,06,...")
@bot.message_handler(func=lambda msg: len(msg.text.strip().split())==3 and all(s.isdigit() for s in msg.text.strip().split()))
def phan_tich_ngay_yeu_cau(msg): try: tach=msg.text.strip().split(); ngay_moc=datetime(int(tach[2]),int(tach[1]),int(tach[0])); bot.send_message(msg.chat.id,"🔄 Truy cập an toàn luân phiên nguồn & chờ nhẹ lấy đủ dữ liệu..."); tap_hop=[]; [ (kq:=lay_an_toan(ngay_moc-timedelta(days=lui))) and tap_hop.extend(kq); time.sleep(random.uniform(0.22,0.4)) for lui in range(60) ]; if len(tap_hop)<40: bot.send_message(msg.chat.id,f"ℹ️ Đã gom {len(tap_hop)} số, gửi bổ sung vài ngày theo mẫu là đủ phân tích ngay nhé!"); return; top3,top20=tinh_diem_chuan(tap_hop); ngay_sau=ngay_moc+timedelta(days=1); bot.send_message(msg.chat.id,f"""✅===== KẾT QUẢ PHÂN TÍCH =====\n📅 Đến ngày: {ngay_moc.strftime('%d/%m/%Y')} → THAM KHẢO NGÀY: {ngay_sau.strftime('%d/%m/%Y')}\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n🏆🥇{top3[0][0]}: {top3[0][1]} lần | Tần suất cao nhất + chu kỳ đều ổn nhất\n🥈{top3[1][0]}: {top3[1][1]} lần | Quy luật tốt thứ hai\n🥉{top3[2][0]}: {top3[2][1]} lần | Đáng tin cậy thứ ba\n📋20 đuôi tốt khác: ▫️{'  ▫️'.join(top20)}\n⚠️Chỉ mang tính tham khảo vui chơi giải trí!""") except Exception as e: bot.send_message(msg.chat.id,"⚠️ Nhập đúng: Ngày Tháng Năm cách khoảng trắng nhé!")
API_KEY_ALPHA=["SYHGO5Z8DE4RAU8E","52MWBOYE0RSLQE8E","N8TO30AM8DVVGDE7"]; DANH_SACH_UPCOM=["SHB","HDB","TCB","VPB","MBB","SSB","EIB","VIX","MBS","VCI","SSI","ACB","BID","VCB"]
def lay_danh_gia_cp(ma): [ (res:=requests.get(f"https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol={ma}.VN&apikey={apikey}&outputsize=compact",timeout=10).json()) and ("Time Series" in res) and (ds_ngay:=sorted(res["Time Series (Daily)"].items(),reverse=True)[:14]) and (gia_dong:=[float(v["4. close"]) for _,v in ds_ngay]) and len(gia_dong)>=10 and (ema5:=round(sum(gia_dong[:5])/5,2)) and (ema10:=round(sum(gia_dong[:10])/10,2)) and (xu_huong:="📈 Tăng tốt" if ema5>ema10 else "📉 Cần theo dõi") and (diem:=round(min(10,5+(ema5-ema10)*100/ema10),1)) and (gia_hien_tai:=gia_dong[0]) and (chot_loi:=round(gia_hien_tai*1.03,2)) and (cat_lo:=round(gia_hien_tai*0.97,2)) and return f"{ma} | Điểm: {diem}/10 | {xu_huong}\nGiá: {gia_hien_tai:,} | Chốt lời: {chot_loi:,} | Cắt lỗ: {cat_lo:,}" for apikey in API_KEY_ALPHA ]; return f"⚠️ Chưa lấy được dữ liệu {ma}"
@bot.message_handler(func=lambda msg: msg.text.strip()=="Danh gia UPCOM")
def danh_gia_nhom(msg): if msg.chat.id!=CHAT_ID: return; bot.send_message(CHAT_ID,"🔄 Đang đánh giá nhóm UPCOM theo thang điểm 10..."); ketqua=[lay_danh_gia_cp(ma) for ma in DANH_SACH_UPCOM]; [time.sleep(1.2) for _ in ketqua]; bot.send_message(CHAT_ID,"\n\n".join(ketqua))
@bot.message_handler(func=lambda msg: msg.text.strip().startswith("DG "))
def danh_gia_mot_ma(msg): if msg.chat.id!=CHAT_ID: return; ma=msg.text.strip()[3:].upper().strip(); bot.send_message(CHAT_ID,lay_danh_gia_cp(ma))
@bot.message_handler(func=lambda msg: msg.text.strip()=="Trang thai")
def kiem_tra(msg): if msg.chat.id!=CHAT_ID: return; bot.send_message(CHAT_ID,"✅ Đang hoạt động: chống chặn hiệu quả, luân phiên nguồn, nhận lưu dữ liệu bạn gửi bổ sung, phân tích xổ số & đánh giá cổ phiếu đủ chức năng!")
while True: try: bot.polling(none_stop=True,interval=5,timeout=60) except Exception as e: print(f"Kết nối lại: {e}"); time.sleep(10)
